common: &shared
  adapter: postgresql
  encoding: utf-8
  host: 127.0.0.1
  database: hotel
  pool: 5
  username: postgres
  password: P@ssw0rd

development:
 <<: *shared

test:
 <<: *shared

production:
 <<: *shared

