development:
  url: 'http://127.0.0.1:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'

test:
  url: 'http://127.0.0.1:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'

production:
  url: 'http://127.0.0.1:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'