development:
  url: 'http://jasperserver:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'

test:
  url: 'http://jasperserver:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'

production:
  url: 'http://jasperserver:8080'
  username: 'jasperadmin'
  password: 'jasperadmin'